In [3]:
import pandas as pd
import numpy as np
from pathlib import Path

print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)
print("Notebook is ready!")

Pandas version: 3.1.0
NumPy version: 2.4.6
Notebook is ready!

In [2]:
print("Sales Performance Dashboard")
print("Python environment is ready!")

Sales Performance Dashboard
Python environment is ready!

In [4]:
import pandas as pd
import numpy as np
from pathlib import Path

# Locate the project folder
PROJECT_DIR = Path.cwd().parent

# Locate the raw data folder
raw_folder = PROJECT_DIR / "data" / "raw"

# Find CSV files
csv_files = list(raw_folder.glob("*.csv"))

print("Project folder:", PROJECT_DIR)
print("CSV files found:", len(csv_files))

# Stop if the CSV is missing
if not csv_files:
    raise FileNotFoundError(
        "No CSV found. Check that the file is inside data/raw."
    )

# Load the dataset
file_path = csv_files[0]
df = pd.read_csv(file_path, encoding="latin1")

print("\nDataset loaded successfully!")
print("Rows and columns:", df.shape)

Project folder: c:\Users\vishn\Downloads\sales-performance-dashboard
CSV files found: 1

Dataset loaded successfully!
Rows and columns: (9994, 21)

In [5]:
print("Total number of columns:", len(df.columns))
print("\nColumn names:\n")

for column in df.columns:
    print(column)

Total number of columns: 21

Column names:

Row ID
Order ID
Order Date
Ship Date
Ship Mode
Customer ID
Customer Name
Segment
Country
City
State
Postal Code
Region
Product ID
Category
Sub-Category
Product Name
Sales
Quantity
Discount
Profit

In [6]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [7]:
df.head(10)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
5,6,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,7,0.00,14.1694
6,7,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.2800,4,0.00,1.9656
7,8,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6,0.20,90.7152
8,9,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.5040,3,0.20,5.7825
9,10,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.9000,5,0.00,34.4700

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   str
 3   Ship Date      9994 non-null   str
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), str(15)
memory usage: 1.6 MB

In [9]:
df[["Sales", "Quantity", "Discount", "Profit"]].describe()

              Sales     Quantity     Discount       Profit
count   9994.000000  9994.000000  9994.000000  9994.000000
mean     229.858001     3.789574     0.156203    28.656896
std      623.245101     2.225110     0.206452   234.260108
min        0.444000     1.000000     0.000000 -6599.978000
25%       17.280000     2.000000     0.000000     1.728750
50%       54.490000     3.000000     0.200000     8.666500
75%      209.940000     5.000000     0.200000    29.364000
max    22638.480000    14.000000     0.800000  8399.976000

In [10]:
# Count missing values in every column
missing_values = df.isnull().sum()

print("Missing values by column:")
print(missing_values)

print("\nTotal missing values:", missing_values.sum())

Missing values by column:
Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

Total missing values: 0

In [11]:
# Count exact duplicate rows
duplicate_count = df.duplicated().sum()

print("Exact duplicate rows:", duplicate_count)

Exact duplicate rows: 0

In [12]:
print("Duplicate Row IDs:", df["Row ID"].duplicated().sum())

Duplicate Row IDs: 0

In [13]:
# Parse dates without modifying the original DataFrame
order_dates = pd.to_datetime(
    df["Order Date"],
    errors="coerce"
)

ship_dates = pd.to_datetime(
    df["Ship Date"],
    errors="coerce"
)

print("Invalid order dates:", order_dates.isna().sum())
print("Invalid ship dates:", ship_dates.isna().sum())

print(
    "Orders shipped before order date:",
    (ship_dates < order_dates).sum()
)

print("\nNegative sales rows:", (df["Sales"] < 0).sum())
print("Negative quantity rows:", (df["Quantity"] < 0).sum())
print("Negative profit rows:", (df["Profit"] < 0).sum())
print(
    "Discounts outside 0–1:",
    (~df["Discount"].between(0, 1)).sum()
)

Invalid order dates: 0
Invalid ship dates: 0
Orders shipped before order date: 0

Negative sales rows: 0
Negative quantity rows: 0
Negative profit rows: 1871
Discounts outside 0–1: 0

In [14]:
df_clean = df.copy()

print("Original dataset shape:", df.shape)
print("Cleaning dataset shape:", df_clean.shape)

Original dataset shape: (9994, 21)
Cleaning dataset shape: (9994, 21)

In [15]:
df_clean.columns = (
    df_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(r"[\s-]+", "_", regex=True)
)

print(df_clean.columns.tolist())

['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode', 'customer_id', 'customer_name', 'segment', 'country', 'city', 'state', 'postal_code', 'region', 'product_id', 'category', 'sub_category', 'product_name', 'sales', 'quantity', 'discount', 'profit']

In [16]:
text_columns = df_clean.select_dtypes(
    include=["str", "object", "string"]
).columns

for column in text_columns:
    df_clean[column] = df_clean[column].str.strip()

print("Whitespace cleanup completed.")
print("Text columns cleaned:", len(text_columns))

Whitespace cleanup completed.
Text columns cleaned: 15

In [17]:
df_clean["order_date"] = pd.to_datetime(
    df_clean["order_date"],
    errors="raise"
)

df_clean["ship_date"] = pd.to_datetime(
    df_clean["ship_date"],
    errors="raise"
)

print(df_clean[["order_date", "ship_date"]].dtypes)
print("\nFirst five order dates:")
print(df_clean["order_date"].head())

order_date    datetime64[us]
ship_date     datetime64[us]
dtype: object

First five order dates:
0   2016-11-08
1   2016-11-08
2   2016-06-12
3   2015-10-11
4   2015-10-11
Name: order_date, dtype: datetime64[us]

In [18]:
print("Dataset shape:", df_clean.shape)

print("\nMissing values:", df_clean.isnull().sum().sum())

print("Exact duplicate rows:", df_clean.duplicated().sum())

print(
    "Duplicate row IDs:",
    df_clean["row_id"].duplicated().sum()
)

print(
    "Invalid order dates:",
    df_clean["order_date"].isna().sum()
)

print(
    "Invalid ship dates:",
    df_clean["ship_date"].isna().sum()
)

print("\nCleaned data types:")
df_clean.info()

Dataset shape: (9994, 21)

Missing values: 0
Exact duplicate rows: 0
Duplicate row IDs: 0
Invalid order dates: 0
Invalid ship dates: 0

Cleaned data types:
<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   row_id         9994 non-null   int64
 1   order_id       9994 non-null   str
 2   order_date     9994 non-null   datetime64[us]
 3   ship_date      9994 non-null   datetime64[us]
 4   ship_mode      9994 non-null   str
 5   customer_id    9994 non-null   str
 6   customer_name  9994 non-null   str
 7   segment        9994 non-null   str
 8   country        9994 non-null   str
 9   city           9994 non-null   str
 10  state          9994 non-null   str
 11  postal_code    9994 non-null   int64
 12  region         9994 non-null   str
 13  product_id     9994 non-null   str
 14  category       9994 non-null   str
 15  sub_category   9994 non-null   str
 16  product_name   9994 non-null   str
 17  sales          9994 non-null   float64
 18  quantity       9994 non-null   int64
 19  discount       9994 non-null   float64
 20  profit         9994 non-null   float64
dtypes: datetime64[us](2), float64(3), int64(3), str(13)
memory usage: 1.6 MB

In [19]:
output_folder = PROJECT_DIR / "data" / "processed"
output_folder.mkdir(parents=True, exist_ok=True)

output_file = output_folder / "superstore_cleaned.csv"

df_clean.to_csv(output_file, index=False)

print("Cleaned dataset saved successfully!")
print("Saved location:", output_file)
print("Rows exported:", len(df_clean))

Cleaned dataset saved successfully!
Saved location: c:\Users\vishn\Downloads\sales-performance-dashboard\data\processed\superstore_cleaned.csv
Rows exported: 9994

In [20]:
df_check = pd.read_csv(output_file)

print("File exists:", output_file.exists())
print("Exported shape:", df_check.shape)
print("Exported columns:")
print(df_check.columns.tolist())

File exists: True
Exported shape: (9994, 21)
Exported columns:
['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode', 'customer_id', 'customer_name', 'segment', 'country', 'city', 'state', 'postal_code', 'region', 'product_id', 'category', 'sub_category', 'product_name', 'sales', 'quantity', 'discount', 'profit']